# Generated by Django 2.2.7 on 2019-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YT_videos',
            fields=[
                ('videoId', models.CharField(help_text='Unique video ID', max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Video title', max_length=100)),
                ('description', models.CharField(help_text='Short description of the video', max_length=255)),
                ('publishing_date', models.DateTimeField(help_text='Date and time when the video was published')),
                ('default_thumbnail', models.URLField(help_text='Default thumbnail URL')),
                ('medium_thumbnail', models.URLField(help_text='Medium resolution thumbnail URL')),
                ('high_thumbnail', models.URLField(help_text='High resolution thumbnail URL')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
